import extractionv4 as extract

def get_fragments(image):
    extract_process = extract.SignatureExtraction(image, 8, 4, 128)
    avg_lum_list = []
    avg_sing_list = []
    std_lum_list = []
    std_sing_list = []
    rot0 = extract_process.get_blocks()
    rot90, rot180, rot270 = extract_process.basic_rotations(rot0)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 0, 0, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 1, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 2, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 3, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 4, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 5, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 6, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 7, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 8, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 9, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 10, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 11, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 0, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 1, 1, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 2, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 3, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 4, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 5, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 6, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 7, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 8, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 9, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 10, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 11, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 1, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 2, 2, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 3, 2, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 4, 2, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 5, 2, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 6, 2, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 7, 2, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 8, 2, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 9, 2, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 10, 2, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 11, 2, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 2, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 2, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 2, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 3, 3, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 4, 3, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 5, 3, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 6, 3, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 7, 3, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 8, 3, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 9, 3, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 10, 3, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 11, 3, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 3, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 3, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 3, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 4, 4, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 5, 4, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 6, 4, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 7, 4, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 8, 4, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 9, 4, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 10, 4, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 11, 4, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 4, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 4, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 4, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 5, 5, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 6, 5, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 7, 5, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 8, 5, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 9, 5, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 10, 5, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 11, 5, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 5, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 5, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 5, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 6, 6, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 7, 6, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 8, 6, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 9, 6, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 10, 6, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 11, 6, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 6, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 6, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 6, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 7, 7, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 8, 7, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 9, 7, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 10, 7, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 11, 7, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 7, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 7, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 7, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 8, 8, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 9, 8, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 10, 8, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 11, 8, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 8, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 8, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 8, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 9, 9, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 10, 9, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 11, 9, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 9, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 9, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 9, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 10, 10, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 11, 10, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 10, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 10, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 10, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 11, 11, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 11, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 11, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 11, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 12, 12, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 12, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 12, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 13, 13, 1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 13, 0)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)


    avg_lum, std_lum, avg_sing, std_sing = extract_process.get_fragment(rot0, rot90, rot180, rot270, 14, 14, -1)
    avg_lum_list.append(avg_lum)
    avg_sing_list.append(avg_sing)
    std_lum_list.append(std_lum)
    std_sing_list.append(std_sing)

    return avg_lum_list, std_lum_list, avg_sing_list, std_sing_list